import React, { useState, useEffect } from 'react';
import { auditService } from '../services/auditService';
import { LoadingSpinner } from '../components/LoadingSpinner';
import { ErrorMessage } from '../components/ErrorMessage';
import { EmptyState } from '../components/EmptyState';
import { FileText, Filter, RefreshCw, Activity } from 'lucide-react';

export const AuditLogsPage = () => {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Filters
  const [selectedEventType, setSelectedEventType] = useState('ALL');

  const fetchAuditLogs = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await auditService.getAuditLogs();
      setLogs(Array.isArray(data) ? data : []);
    } catch (err) {
      setError(err.response?.data?.message || err.message || 'Failed to fetch audit log records');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAuditLogs();
  }, []);

  const eventTypes = Array.from(new Set(logs.map((l) => l.eventType).filter(Boolean)));

  const filteredLogs = logs.filter((log) => {
    if (selectedEventType !== 'ALL' && log.eventType !== selectedEventType) {
      return false;
    }
    return true;
  });

  const getEventBadge = (type) => {
    switch (type) {
      case 'PURCHASE_CREATED':
        return 'bg-emerald-950 text-emerald-400 border-emerald-800/60';
      case 'TRANSFER_CREATED':
        return 'bg-blue-950 text-blue-400 border-blue-800/60';
      case 'ASSIGNMENT_CREATED':
        return 'bg-purple-950 text-purple-400 border-purple-800/60';
      case 'EXPENDITURE_CREATED':
        return 'bg-red-950 text-red-400 border-red-800/60';
      default:
        return 'bg-slate-800 text-slate-300 border-slate-700';
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <h1 className="text-2xl font-bold text-slate-100 flex items-center gap-2">
            <FileText className="w-6 h-6 text-amber-400" /> System Audit Trail
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Asynchronous persistent event audit log generated by RabbitMQ event bus
          </p>
        </div>

        {/* Filter controls */}
        <div className="flex flex-wrap items-center gap-3 bg-slate-900 p-2.5 rounded-xl border border-slate-800">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 px-2">
            <Filter className="w-3.5 h-3.5 text-amber-400" /> Filter Event:
          </div>

          <select
            value={selectedEventType}
            onChange={(e) => setSelectedEventType(e.target.value)}
            className="bg-slate-950 text-slate-200 border border-slate-800 text-xs rounded-lg px-3 py-1.5 outline-none focus:border-amber-500/50"
          >
            <option value="ALL">All Event Types</option>
            {eventTypes.map((type) => (
              <option key={type} value={type}>
                {type}
              </option>
            ))}
          </select>

          <button
            onClick={fetchAuditLogs}
            title="Refresh Audit Logs"
            className="p-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-colors"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {loading && <LoadingSpinner text="Querying audit log repository..." />}

      {error && <ErrorMessage message={error} onRetry={fetchAuditLogs} />}

      {!loading && !error && filteredLogs.length === 0 && (
        <EmptyState title="No audit logs found" description="No audit log events recorded yet." icon={Activity} />
      )}

      {!loading && !error && filteredLogs.length > 0 && (
        <div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-hidden shadow-lg">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-950/80 border-b border-slate-800 text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  <th className="py-3.5 px-6">Log ID</th>
                  <th className="py-3.5 px-6">Event Type</th>
                  <th className="py-3.5 px-6">Event UUID</th>
                  <th className="py-3.5 px-6">Entity / Details</th>
                  <th className="py-3.5 px-6">Created By</th>
                  <th className="py-3.5 px-6">Timestamp</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-sm">
                {filteredLogs.map((log) => (
                  <tr key={log.id} className="hover:bg-slate-800/40 transition-colors">
                    <td className="py-3.5 px-6 font-mono text-xs text-slate-400">#{log.id}</td>
                    <td className="py-3.5 px-6">
                      <span className={`inline-flex items-center px-2.5 py-0.5 rounded text-[10px] font-bold border ${getEventBadge(log.eventType)}`}>
                        {log.eventType}
                      </span>
                    </td>
                    <td className="py-3.5 px-6 font-mono text-xs text-slate-400 truncate max-w-[140px]">
                      {log.eventId || 'N/A'}
                    </td>
                    <td className="py-3.5 px-6 text-xs text-slate-200">
                      {log.details || `Entity ID: ${log.entityId || 'N/A'}`}
                    </td>
                    <td className="py-3.5 px-6 text-xs text-slate-400 font-mono">
                      User #{log.createdBy || 'SYSTEM'}
                    </td>
                    <td className="py-3.5 px-6 text-xs text-slate-400 font-mono">
                      {log.createdAt ? new Date(log.createdAt).toLocaleString() : 'N/A'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
};
